/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as CheckoutBookingIdRouteImport } from './routes/checkout.$bookingId'
import { Route as BookServiceIdRouteImport } from './routes/book.$serviceId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AgentsApplyRouteImport } from './routes/agents.apply'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const CheckoutBookingIdRoute = CheckoutBookingIdRouteImport.update({
  id: '/checkout/$bookingId',
  path: '/checkout/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookServiceIdRoute = BookServiceIdRouteImport.update({
  id: '/book/$serviceId',
  path: '/book/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsApplyRoute = AgentsApplyRouteImport.update({
  id: '/agents/apply',
  path: '/agents/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/ai': typeof AiRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRouteWithChildren
  '/agents/apply': typeof AgentsApplyRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/ai': typeof AiRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRouteWithChildren
  '/agents/apply': typeof AgentsApplyRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/ai': typeof AiRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRouteWithChildren
  '/agents/apply': typeof AgentsApplyRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$serviceId': typeof BookServiceIdRoute
  '/checkout/$bookingId': typeof CheckoutBookingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/ai'
    | '/bookings'
    | '/login'
    | '/services'
    | '/agents/apply'
    | '/api/chat'
    | '/book/$serviceId'
    | '/checkout/$bookingId'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/ai'
    | '/bookings'
    | '/login'
    | '/services'
    | '/agents/apply'
    | '/api/chat'
    | '/book/$serviceId'
    | '/checkout/$bookingId'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/ai'
    | '/bookings'
    | '/login'
    | '/services'
    | '/agents/apply'
    | '/api/chat'
    | '/book/$serviceId'
    | '/checkout/$bookingId'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AiRoute: typeof AiRoute
  BookingsRoute: typeof BookingsRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AgentsApplyRoute: typeof AgentsApplyRoute
  ApiChatRoute: typeof ApiChatRoute
  BookServiceIdRoute: typeof BookServiceIdRoute
  CheckoutBookingIdRoute: typeof CheckoutBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/checkout/$bookingId': {
      id: '/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/checkout/$bookingId'
      preLoaderRoute: typeof CheckoutBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$serviceId': {
      id: '/book/$serviceId'
      path: '/book/$serviceId'
      fullPath: '/book/$serviceId'
      preLoaderRoute: typeof BookServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/apply': {
      id: '/agents/apply'
      path: '/agents/apply'
      fullPath: '/agents/apply'
      preLoaderRoute: typeof AgentsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AiRoute: AiRoute,
  BookingsRoute: BookingsRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AgentsApplyRoute: AgentsApplyRoute,
  ApiChatRoute: ApiChatRoute,
  BookServiceIdRoute: BookServiceIdRoute,
  CheckoutBookingIdRoute: CheckoutBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
